title = ""
baseURL = "http://example.org/"
languageCode = 'en-us'
theme = "centauri"
disableKinds = ["taxonomy", "term"]
math = true

[params]
    author = "J.D. Levy"
    description = "Mathematical Misadventures for Malcontent Miscreants."
    # favicon = "favicon.ico"
    [params.footer]
        text = "J.D. Levy"
        text1 = "test" # add {{.text}} to footer partial if needed
        url = "http://github.com/deadmoose14"
    [params.style] # appearance settings, links to scss in assets
        fontFamily = "Fira Code"
        pageWidth = "750px"
        colorBG = "#191724"
        colorFG = "#ffffff"
    [[params.socialIcons]]
        icon = "fas fa-envelope"
        title = "E-mail"
        url = "mailto:levy@jdlmath.com"

[permalinks]
    "/" = "/:filename"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "About"
        url = "/about"
        weight = 2
    [[menu.main]]
        name = "Posts"
        url = "/posts"
        weight = 3
    [[menu.main]]
        name = "Resources"
        url = "/resources"
        weight = 4
    [[menu.main]]
        name = "Contact"
        url = "/contact"
        weight = 5

[markup.goldmark.renderer]
    unsafe = true 
