title = "Centauri"
baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = "centauri"
math = true

[params]
    author = "J. Levy"
    description = "Theme for my class website"
    # favicon = "favicon.ico"
    [params.footer]
        text = "J. Levy"
        url = "http://github.com/deadmoose14"
    [params.style] # appearance settings, links to scss in assets
        fontFamily = "Fira Code" 
        pageWidth = "750px"
        colorBG = "#191724"
        colorFG = "#eb6f92"
    [[params.socialIcons]]
        icon = "fas fa-envelope"
        title = "E-mail"
        url = "mailto:levy@jdlmath.com"

[permalinks]
    "/" = "/:filename"

[menu]
    [[menu.main]]
        name = "About"
        url = "/about"
        weight = 1
    [[menu.main]]
        name = "Posts"
        url = "/posts"
        weight = 2
    [[menu.main]]
        name = "Contact"
        url = "/contact"
        weight = 3

[markup.goldmark.renderer]
    unsafe = true 
